[package]
name = "c2zk-rust-wasm-tests-add-bin"
version = "0.1.0"
edition = "2021"

[dependencies]
c2zk-stdlib = { path = "../../stdlib", features = [] }
c2zk-rust-wasm-tests-add = { path = "../add" }
